import React, { useState } from 'react';
import { ArrowRight, Mail, Phone, ShieldAlert, User } from 'lucide-react';
import { useLocation, useNavigate } from 'react-router-dom';

const RaceRegistration = () => {
  const { state } = useLocation();
  const navigate = useNavigate();
  const [form, setForm] = useState({ name: '', email: '', phone: '', emergencyName: '', emergencyPhone: '' });
  if (!state?.race) return <div className="pt-32 text-center">Race details unavailable. <button onClick={() => navigate('/races')} className="text-primary">Back to races</button></div>;
  const update = event => setForm({ ...form, [event.target.name]: event.target.value });
  const submit = event => { event.preventDefault(); navigate('/payment', { state: { ...state, participant: form } }); };
  return <div className="pt-28 pb-16 min-h-screen max-w-4xl mx-auto px-4"><p className="text-primary text-[10px] font-black uppercase tracking-[0.3em]">Race entry / athlete information</p><h1 className="text-4xl md:text-6xl font-black uppercase italic tracking-tighter mt-2">Enter your <span className="text-primary">details</span></h1><p className="text-gray-500 mt-3">{state.race.title} · {state.race.location}</p><form onSubmit={submit} className="glass-card p-6 md:p-10 mt-10 grid md:grid-cols-2 gap-6"><label className="text-[10px] font-black uppercase tracking-widest text-gray-500">Full name<div className="relative mt-2"><User className="absolute left-4 top-1/2 -translate-y-1/2 text-gray-600" size={17}/><input name="name" required value={form.name} onChange={update} className="input-hero pl-11 py-4"/></div></label><label className="text-[10px] font-black uppercase tracking-widest text-gray-500">Email<div className="relative mt-2"><Mail className="absolute left-4 top-1/2 -translate-y-1/2 text-gray-600" size={17}/><input type="email" name="email" required value={form.email} onChange={update} className="input-hero pl-11 py-4"/></div></label><label className="text-[10px] font-black uppercase tracking-widest text-gray-500">Contact number<div className="relative mt-2"><Phone className="absolute left-4 top-1/2 -translate-y-1/2 text-gray-600" size={17}/><input type="tel" name="phone" required value={form.phone} onChange={update} className="input-hero pl-11 py-4"/></div></label><div className="md:col-span-2 border-t border-white/10 pt-6"><p className="text-primary text-[10px] font-black uppercase tracking-widest flex items-center gap-2"><ShieldAlert size={15}/> Emergency contact</p></div><label className="text-[10px] font-black uppercase tracking-widest text-gray-500">Emergency name<input name="emergencyName" required value={form.emergencyName} onChange={update} className="input-hero mt-2 py-4"/></label><label className="text-[10px] font-black uppercase tracking-widest text-gray-500">Emergency phone<input type="tel" name="emergencyPhone" required value={form.emergencyPhone} onChange={update} className="input-hero mt-2 py-4"/></label><button className="hero-button md:col-span-2 py-4 flex items-center justify-center gap-2">Review payment <ArrowRight size={17}/></button></form></div>;
};
export default RaceRegistration;
